// UniCode — статический реестр иконок.
// Импортируем только реально используемые иконки lucide-react (по имени),
// чтобы бандл не тянул всю библиотеку. Поиск по kebab-case имени.
// Неизвестное имя рендерится как пустой слот (без падения).
import {
  Activity,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Badge,
  Bell,
  BookOpen,
  Box,
  Building,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Code2,
  Columns2,
  Copy,
  CreditCard,
  File,
  FileCode,
  FilePlus,
  Files,
  Folder,
  FolderOpen,
  Ghost,
  GitBranch,
  GitCommitHorizontal,
  Github,
  Globe,
  Grid,
  Heading,
  Home,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Linkedin,
  List,
  Lock,
  LogOut,
  Maximize2,
  Megaphone,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  OctagonAlert,
  Package,
  Pencil,
  Pill,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Rocket,
  RotateCw,
  Search,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Sun,
  Tag,
  Terminal,
  Text,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Twitter,
  Type,
  Umbrella,
  User,
  UserPlus,
  Users,
  Variable,
  X,
  Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

const REGISTRY: Record<string, FC<LucideProps>> = {
  'activity': Activity,
  'arrow-down-up': ArrowDownUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'badge': Badge,
  'bell': Bell,
  'book-open': BookOpen,
  'box': Box,
  'building': Building,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'circle-check': CircleCheck,
  'clock': Clock,
  'cloud': Cloud,
  'code': Code,
  'code-2': Code2,
  'columns-2': Columns2,
  'copy': Copy,
  'credit-card': CreditCard,
  'file': File,
  'file-code': FileCode,
  'file-plus': FilePlus,
  'files': Files,
  'folder': Folder,
  'folder-open': FolderOpen,
  'ghost': Ghost,
  'git-branch': GitBranch,
  'git-commit-horizontal': GitCommitHorizontal,
  'github': Github,
  'globe': Globe,
  'grid': Grid,
  'heading': Heading,
  'home': Home,
  'info': Info,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  'linkedin': Linkedin,
  'list': List,
  'lock': Lock,
  'log-out': LogOut,
  'maximize-2': Maximize2,
  'megaphone': Megaphone,
  'menu': Menu,
  'message-square': MessageSquare,
  'minus': Minus,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'mouse-pointer-click': MousePointerClick,
  'octagon-alert': OctagonAlert,
  'package': Package,
  'pencil': Pencil,
  'pill': Pill,
  'play': Play,
  'plus': Plus,
  'radio': Radio,
  'refresh-cw': RefreshCw,
  'rocket': Rocket,
  'rotate-cw': RotateCw,
  'search': Search,
  'settings': Settings,
  'sliders-horizontal': SlidersHorizontal,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'square': Square,
  'sun': Sun,
  'tag': Tag,
  'terminal': Terminal,
  'text': Text,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'twitter': Twitter,
  'type': Type,
  'umbrella': Umbrella,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'variable': Variable,
  'x': X,
  'zap': Zap,
};

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: string;
}

export function Icon({ name, size = 18, strokeWidth = 2, color = 'currentColor', style, ...rest }: IconProps) {
  const Comp = REGISTRY[name];
  if (!Comp) return <span style={{ display: 'inline-flex', width: size, height: size }} />;
  return (
    <Comp
      size={size}
      strokeWidth={strokeWidth}
      color={color}
      style={{ display: 'block', flexShrink: 0, ...style }}
      {...rest}
    />
  );
}
